DROP TABLE RECURSIVE_REFERENCE IF EXISTS;
DROP TABLE REMINDER IF EXISTS;

CREATE TABLE REMINDER
(
    ID BIGINT AUTO_INCREMENT not null primary key,	
	REMINDER_DATE DATE not null,
	REMINDER_TIME TIME not null,
	TASK VARCHAR(255) not null,
	SNOOZE_TIME TIME,
	STATUS CHAR(7),
	RECURSIVE_ID INT
);

CREATE TABLE RECURSIVE_REFERENCE
(
	ID BIGINT not null primary key,
	MONDAY BIT,
	TUESDAY BIT,
	WEDNESDAY BIT,
	THURSDAY BIT,
	FRIDAY BIT,
	SATURDAY BIT,
	SUNDAY BIT,
	MONTHLY SMALLINT
);

INSERT INTO REMINDER
	 (ID, TASK, SNOOZE_TIME, REMINDER_DATE, STATUS, RECURSIVE_ID, REMINDER_TIME) 
VALUES 
	('1', 'Welcome to jvege', NULL, '2000-01-01', NULL, NULL, '12:00:00');
